# Generated by Django 5.2.14 on 2026-05-24 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_prompt', models.TextField(help_text='Original user-entered prompt')),
                ('prompt_type', models.CharField(choices=[('general', 'General AI'), ('coding', 'Coding'), ('sql', 'SQL'), ('uiux', 'UI/UX'), ('image', 'Image Generation'), ('api', 'API Generation'), ('devops', 'DevOps'), ('documentation', 'Documentation'), ('architecture', 'Architecture')], default='general', max_length=50)),
                ('ai_provider', models.CharField(default='openai', max_length=50)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('optimized_prompt', models.TextField(blank=True)),
                ('suggested_role', models.TextField(blank=True)),
                ('improvements_made', models.JSONField(default=list)),
                ('output_structure', models.TextField(blank=True)),
                ('token_count', models.IntegerField(default=0)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_saved', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Optimization Record',
                'verbose_name_plural': 'Optimization Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prompt_type'], name='prompt_opti_prompt__bbe0e6_idx'), models.Index(fields=['ai_provider'], name='prompt_opti_ai_prov_5f1170_idx'), models.Index(fields=['created_at'], name='prompt_opti_created_89b02e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('prompt_type', models.CharField(choices=[('general', 'General AI'), ('coding', 'Coding'), ('sql', 'SQL'), ('uiux', 'UI/UX'), ('image', 'Image Generation'), ('api', 'API Generation'), ('devops', 'DevOps'), ('documentation', 'Documentation'), ('architecture', 'Architecture')], max_length=50)),
                ('optimized_prompt', models.TextField()),
                ('suggested_role', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('optimization_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_prompt', to='prompt_optimizer.optimizationrecord')),
            ],
            options={
                'verbose_name': 'Saved Prompt',
                'verbose_name_plural': 'Saved Prompts',
                'ordering': ['-created_at'],
            },
        ),
    ]
