# Generated by Django 5.2.14 on 2026-05-24 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('total_optimizations', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('optimizations_by_type', models.JSONField(default=dict)),
                ('optimizations_by_provider', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
